### ISSUE TITLE
cpu only mode

### ISSUE THREAD

**Issue by kathrinrin** [gustavla/autocolorize#1]
I installed caffe in cpu-only mode on my laptop, which is sufficient for my use cases and also much easier to install. autocolorize by standard only works in gpu mode, it would be great if that would be parametrized! (Thanks to the source code I got it running in cpu-only mode (great!), I just uncommented the set parameter section).

**Comment by gustavla** [comment]
Good point! I added the option to select `--device cpu` or `-d cpu`.

**Comment by kathrinrin** [comment]
Great, thanks so much!
