### ISSUE TITLE
Same problem as #8 when running autocolorize

### ISSUE THREAD

**Issue by ZiyangLiu** [gustavla/autocolorize#10]
Hello, 
I have the same problem as #8. 
I try to run: autocolorize grayscale.png -o colorized.png
I already run: rm ~/.autocolorize/autocolorize.caffemodel.h5 as told in #8 
But the autocolorize still aborts. 
In #8 it shows: 7 7 (102760448).
My results shows: 
F0906 12:04:59.769284 24443 hdf5.cpp:79] Check failed: blob_dims == blob->shape() Cannot load blob from hdf5; shape mismatch. Source shape is 1024 12417 (12715008) target shape is 1024 12417 1 1 (12715008)
Does anyone know what is going on?
Thanks.

**Comment by gustavla** [comment]
I noticed one more thing I needed to change. Please try removing the file again and adding it back. Sorry about that!

Gustav

**Comment by abhaymittal** [comment]
Thanks, it runs now!
