### ISSUE TITLE
calc_rgb param argument splitting

### ISSUE THREAD

**Issue by rkern** [gustavla/autocolorize#2]
https://github.com/gustavla/autocolorize/blob/master/autocolorize/__main__.py#L130

This won't work when the desired `h_method` is `expectation-cf` since the delimiting character is in one of the components.

**Comment by gustavla** [comment]
Ah, you are right. Caused by last-minute name change. I will push a fix tonight. Thanks for the catch!

**Comment by gustavla** [comment]
Note that I changed the splitting delimiter to `:`, so you can do for instance `expectation:expectation-cf`.
