### ISSUE TITLE
installing dependencies

### ISSUE THREAD

**Issue by jmokoistinen** [gustavla/autocolorize#5]
I have ubuntu 16.04.
Seems the dependencies are quite hard to install.
(protobuf, ... cv 3.0.0) either wrong headers/too new compiler... etc. 
any better tutorial on that? 
How to install all from the source and in which order?

**Comment by gustavla** [comment]
There are extensive installation options at the Caffe website: http://caffe.berkeleyvision.org/installation.html

The extra layers should not make it any harder, except possibly the extended data loading layer. However, that one can easily be skipped and replaced with the built-in one.
