### ISSUE TITLE
Training - ExtendedImageDataLayer has no member named ‘iter’

### ISSUE THREAD

**Issue by AruniRC** [gustavla/autocolorize#7]
Hi Gustav,

Trying to train the network from scratch using your extended data layer (I did not find any quick way to avoid using that layer):

I am stuck at an error in when doing `make all` in the caffe directory.
It seems that the `ExtendedImageDataLayer` class is missing a lot of member attributes.
Could you please help?

```
CXX src/caffe/layers/extended_image_data_layer.cpp
src/caffe/layers/extended_image_data_layer.cpp: In instantiation of ‘void caffe::ExtendedImageDataLayer<Dtype>::DataLayerSetUp(const std::vector<caffe::Blob<Dtype>*>&, const std::vector<caffe::Blob<Dtype>*>&) [with Dtype = float]’:
src/caffe/layers/extended_image_data_layer.cpp:703:1:   required from here
src/caffe/layers/extended_image_data_layer.cpp:574:21: error: ‘class caffe::ExtendedImageDataLayer<float>’ has no member named ‘PREFETCH_COUNT’
   for (int i = 0; i < this->PREFETCH_COUNT; ++i) {
                     ^
src/caffe/layers/extended_image_data_layer.cpp:575:5: error: ‘__gnu_cxx::__alloc_traits<std::allocator<boost::shared_ptr<caffe::Batch<float> > > >::value_type’ has no member named ‘data_’
     this->prefetch_[i].data_.Reshape(top_shape);
```

**Comment by kenshinzh** [comment]
@gustavla I have met the same issue. Did you resolve it? @AruniRC

**Comment by LPCelite** [comment]
@gustavla 
1. find the base_data_layer.hpp from resource file
2. you will find that there are no PREFETCH_COUNT
3. I guess you caffe version is master, you should change PREFETCH_COUNT to prefecth_.size(), and 
this->prefetch_[i].data_.Reshape(top_shape) to this->prefetch_[i]->data_.Reshape(top_shape);

**Comment by gustavla** [comment]
I've been working on updating the `ExtendedImageDataLayer` to work with Caffe master, and I hope to get it done in the next few days. However, this layer is not essential and can easily be replaced with Caffe's built-in data loading layers.
