### ISSUE TITLE
Error running for a single image

### ISSUE THREAD

**Issue by GMNetto** [gustavla/autocolorize#8]
Hello,

I installed caffe and autocolarize, but when I try to run for a png image(512x512) I get the following error.

F0417 13:52:09.999788  2561 hdf5.cpp:79] Check failed: blob_dims == blob->shape() Cannot load blob from hdf5; shape mismatch. Source shape is 4096 25088 (102760448) target shape is 4096 512 7 7 (102760448)

This causes the code to abort. Does anyone know how to solve this issue?

**Comment by noqcks** [comment]
I am receiving this as well.

**Comment by gustavla** [comment]
I believe that in my personal Caffe I have relaxed the shape match requirements, allowing implicit reshapes. A quick fix is to take the HDF5 file and simply reshape the fc6 filters so that they agree with Caffe. I will look into how best I can fix this on my end.

**Comment by enzoleo** [comment]
The Caffe source code about shape match changed in release v1.0: [#4630](https://github.com/BVLC/caffe/pull/4630). Maybe the previous Caffe version works well.

**Comment by kenshinzh** [comment]
met the same issue as GMNetto. @GMNetto Do you fix the issue with the latest caffe version?

**Comment by kjc10** [comment]
Hello, I am currently trying to use autocolorize and I am having this problem as well. Can anyone tell me what they did in order to get it to work?

**Comment by jcrdubois** [comment]
@gustavla I'm also running into this issue. Would you mind expanding a bit on your "quick fix" so I can get the code running -- I'm not sure what you mean exactly.

**Comment by gustavla** [comment]
I have updated the weights file on the server to have shapes that should work without modifying Caffe. You just have to remove the cached weights file and the new will be automatically downloaded:

    rm ~/.autocolorize/autocolorize.caffemodel.h5

Really sorry this took so long.
